FROM openjdk:11

ADD target/spring-boot-crud-operation-0.0.1-SNAPSHOT.jar spring-boot-crud-operation.jar
ADD target/agrihelper-0.0.1-SNAPSHOT.jar agrihelper.jar

ENTRYPOINT ["java", "-jar", "first.jar"]
